export const ADD_ONEUSER = 'ADD_ONEUSER';
export const ALL_DATAUSER = 'ALL_DATAUSER';
export const FETCH_FLIGHT = 'FETCH_FLIGHT';
export const ROUTE_START = 'ROUTE_START';
export const SEARCH_DATAUSER = 'SEARCH_DATAUSER';

