export const SET_COUNTER = 'SET_COUNTER';
export const CLEAR_COUNTER = 'CLEAR_COUNTER';
export const INCRENENT_COUNTER = 'INCRENENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const ADDDATA_COUNTER = 'ADDDATA_COUNTER';
export const FETCHDATA = 'FETCHDATA';
export const FETCH_FLIGHT = 'FETCH_FLIGHT';
export const ROUTE_START = 'ROUTE_START';

